import { User, Sticker, ChatConversation, PlatformRule } from './types';

export const INITIAL_USERS: User[] = [
  {
    id: 'user_1',
    name: 'João Silva',
    email: 'joao@email.com',
    country: 'Brasil',
    avatar: 'https://images.unsplash.com/photo-1535713875002-d1d0cf377fde?auto=format&fit=crop&w=150&q=80',
    role: 'user',
    blocked: false,
    balance: 145.50,
    stickersOwned: 342,
    stickersRepeated: 48,
    rating: 4.8,
  },
  {
    id: 'user_2',
    name: 'Maria Santos',
    email: 'maria@email.com',
    country: 'Portugal',
    avatar: 'https://images.unsplash.com/photo-1494790108377-be9c29b29330?auto=format&fit=crop&w=150&q=80',
    role: 'user',
    blocked: false,
    balance: 85.00,
    stickersOwned: 290,
    stickersRepeated: 32,
    rating: 4.9,
  },
  {
    id: 'user_3',
    name: 'Pedro Costa',
    email: 'pedro@email.com',
    country: 'Angola',
    avatar: 'https://images.unsplash.com/photo-1570295999919-56ceb5ecca61?auto=format&fit=crop&w=150&q=80',
    role: 'user',
    blocked: false,
    balance: 210.00,
    stickersOwned: 412,
    stickersRepeated: 61,
    rating: 4.7,
  },
  {
    id: 'user_4',
    name: 'John Miller',
    email: 'john@email.com',
    country: 'EUA',
    avatar: 'https://images.unsplash.com/photo-1500648767791-00dcc994a43e?auto=format&fit=crop&w=150&q=80',
    role: 'user',
    blocked: false,
    balance: 350.00,
    stickersOwned: 180,
    stickersRepeated: 24,
    rating: 4.8,
  },
  {
    id: 'user_5',
    name: 'Juan Gómez',
    email: 'juan@email.com',
    country: 'Espanha',
    avatar: 'https://images.unsplash.com/photo-1507003211169-0a1dd7228f2d?auto=format&fit=crop&w=150&q=80',
    role: 'user',
    blocked: false,
    balance: 190.00,
    stickersOwned: 210,
    stickersRepeated: 15,
    rating: 4.6,
  },
  {
    id: 'user_6',
    name: 'Jean Dupont',
    email: 'jean@email.com',
    country: 'França',
    avatar: 'https://images.unsplash.com/photo-1472099645785-5658abf4ff4e?auto=format&fit=crop&w=150&q=80',
    role: 'user',
    blocked: false,
    balance: 275.50,
    stickersOwned: 310,
    stickersRepeated: 40,
    rating: 4.9,
  },
  {
    id: 'user_admin',
    name: 'Admin Platform',
    email: 'admin@copa.com',
    country: 'Mundo',
    avatar: 'https://images.unsplash.com/photo-1543611747-1b93f69a1941?auto=format&fit=crop&w=150&q=80',
    role: 'admin',
    blocked: false,
    balance: 0.00,
    stickersOwned: 0,
    stickersRepeated: 0,
    rating: 5.0,
  }
];

export const INITIAL_STICKERS: Sticker[] = [
  {
    id: 'sticker_1',
    number: 'QA-01',
    player: 'Lionel Messi',
    country: 'Argentina',
    year: '2022',
    album: 'Qatar 2022',
    type: 'venda',
    price: 350.00,
    condition: 'Novo',
    image: 'messi',
    description: 'Figurinha Extra Legend Gold de Lionel Messi em estado impecável, recém-saída do pacotinho. Item de colecionador extremo.',
    rarity: 'Lendária',
    ownerId: 'user_2',
    ownerName: 'Maria Santos',
    active: true,
    approved: true,
  },
  {
    id: 'sticker_2',
    number: 'CR-07',
    player: 'Cristiano Ronaldo',
    country: 'Portugal',
    year: '2022',
    album: 'Qatar 2022',
    type: 'ambos',
    price: 290.00,
    condition: 'Novo',
    image: 'cr7',
    description: 'Figurinha Legend Bronze do CR7 em excelente estado. Aceito troca por Neymar Gold ou venda direta.',
    rarity: 'Lendária',
    ownerId: 'user_3',
    ownerName: 'Pedro Costa',
    active: true,
    approved: true,
  },
  {
    id: 'sticker_3',
    number: 'NJR-10',
    player: 'Neymar Jr',
    country: 'Brasil',
    year: '2022',
    album: 'Qatar 2022',
    type: 'troca',
    condition: 'Novo',
    image: 'neymar',
    description: 'Tenho repetida do craque brasileiro Neymar Jr. Procuro figurinhas do álbum da Copa de 2018 para trocar.',
    rarity: 'Rara',
    ownerId: 'user_1',
    ownerName: 'João Silva',
    active: true,
    approved: true,
  },
  {
    id: 'sticker_4',
    number: 'KM-10',
    player: 'Kylian Mbappé',
    country: 'França',
    year: '2022',
    album: 'Qatar 2022',
    type: 'venda',
    price: 95.00,
    condition: 'Novo',
    image: 'mbappe',
    description: 'Mbappé original brilhante em ótimo estado. Envio rápido via correio segurado ou entrego em mãos.',
    rarity: 'Rara',
    ownerId: 'user_2',
    ownerName: 'Maria Santos',
    active: true,
    approved: true,
  },
  {
    id: 'sticker_5',
    number: 'VJ-20',
    player: 'Vinícius Júnior',
    country: 'Brasil',
    year: '2022',
    album: 'Qatar 2022',
    type: 'troca',
    condition: 'Novo',
    image: 'vini',
    description: 'Vini Jr brilhante repetido. Quero trocar por qualquer lendária que eu não tenha no meu álbum.',
    rarity: 'Rara',
    ownerId: 'user_1',
    ownerName: 'João Silva',
    active: true,
    approved: true,
  },
  {
    id: 'sticker_6',
    number: 'LM-10',
    player: 'Luka Modrić',
    country: 'Croácia',
    year: '2022',
    album: 'Qatar 2022',
    type: 'venda',
    price: 35.00,
    condition: 'Usado',
    image: 'modric',
    description: 'Modrić comum em bom estado, apenas com marcas leves de manuseio no verso. Preço camarada.',
    rarity: 'Comum',
    ownerId: 'user_3',
    ownerName: 'Pedro Costa',
    active: true,
    approved: true,
  },
  {
    id: 'sticker_7',
    number: 'HK-09',
    player: 'Harry Kane',
    country: 'Inglaterra',
    year: '2022',
    album: 'Qatar 2022',
    type: 'ambos',
    price: 15.00,
    condition: 'Novo',
    image: 'kane',
    description: 'Harry Kane comum do time inglês. Troco por figurinha do escudo do Brasil ou vendo bem barato.',
    rarity: 'Comum',
    ownerId: 'user_2',
    ownerName: 'Maria Santos',
    active: true,
    approved: true,
  },
  {
    id: 'sticker_8',
    number: 'KDB-17',
    player: 'Kevin De Bruyne',
    country: 'Bélgica',
    year: '2022',
    album: 'Qatar 2022',
    type: 'venda',
    price: 40.00,
    condition: 'Novo',
    image: 'debruyne',
    description: 'Kevin de Bruyne brilhante original. Perfeito estado físico, sem riscos.',
    rarity: 'Rara',
    ownerId: 'user_1',
    ownerName: 'João Silva',
    active: true,
    approved: true,
  },
  {
    id: 'sticker_9',
    number: 'RL-09',
    player: 'Robert Lewandowski',
    country: 'Polônia',
    year: '2022',
    album: 'Qatar 2022',
    type: 'venda',
    price: 18.00,
    condition: 'Novo',
    image: 'lewandowski',
    description: 'Artilheiro Lewa, excelente estado para completar seu álbum da Copa.',
    rarity: 'Comum',
    ownerId: 'user_3',
    ownerName: 'Pedro Costa',
    active: true,
    approved: false, // For testing admin moderation screen!
  },
  {
    id: 'sticker_10',
    number: 'JB-22',
    player: 'Jude Bellingham',
    country: 'Inglaterra',
    year: '22',
    album: 'Qatar 2022',
    type: 'venda',
    price: 120.00,
    condition: 'Novo',
    image: 'bellingham',
    description: 'Jude Bellingham Rookie card in pristine condition. Open to solid trade offers or PayPal.',
    rarity: 'Lendária',
    ownerId: 'user_4',
    ownerName: 'John Miller',
    active: true,
    approved: true,
  },
  {
    id: 'sticker_11',
    number: 'PD-26',
    player: 'Pedri',
    country: 'Espanha',
    year: '2022',
    album: 'Qatar 2022',
    type: 'ambos',
    price: 38.00,
    condition: 'Novo',
    image: 'pedri',
    description: 'Cromo brillante de Pedri de España, excelente estado. Busco cromos de Brasil o Argentina para cambiar.',
    rarity: 'Rara',
    ownerId: 'user_5',
    ownerName: 'Juan Gómez',
    active: true,
    approved: true,
  },
  {
    id: 'sticker_12',
    number: 'AG-07',
    player: 'Antoine Griezmann',
    country: 'França',
    year: '2022',
    album: 'Qatar 2022',
    type: 'troca',
    condition: 'Novo',
    image: 'griezmann',
    description: 'Antoine Griezmann du Qatar 2022. Très bon état, stocké à l\'abri du soleil. Envoi soigné et rapide.',
    rarity: 'Rara',
    ownerId: 'user_6',
    ownerName: 'Jean Dupont',
    active: true,
    approved: true,
  }
];

export const INITIAL_RULES: PlatformRule[] = [
  {
    id: 'rule_1',
    title: '🛡️ Encontros em Locais Públicos',
    content: 'Recomendamos fortemente que todas as trocas ou pagamentos em mãos ocorram em shoppings, estádios, estações de metrô ou locais corporativos movimentados. Nunca marque encontros em locais isolados.'
  },
  {
    id: 'rule_2',
    title: '🤝 Política de Troca Justa',
    content: 'Figurinhas consideradas raras (brilhantes) ou lendárias (Legends Gold/Bronze) costumam ter maior valor de mercado. Respeite as propostas dos outros usuários. Enganar colecionadores novatos ou crianças resultará em banimento permanente.'
  },
  {
    id: 'rule_3',
    title: '🚫 Anúncios de Itens Falsos',
    content: 'Qualquer anúncio contendo fotos de figurinhas impressas de forma caseira ou falsificadas sem clara menção será removido. Reincidência ocasionará no bloqueio imediato do perfil do usuário por infração de propriedade intelectual.'
  }
];

export const INITIAL_CHATS: ChatConversation[] = [
  {
    id: 'chat_1',
    stickerId: 'sticker_1',
    buyerId: 'user_1',
    sellerId: 'user_2',
    buyerName: 'João Silva',
    sellerName: 'Maria Santos',
    stickerName: 'Lionel Messi QA-01',
    stickerImage: 'messi',
    stickerPrice: 350.00,
    stickerType: 'venda',
    status: 'active',
    messages: [
      {
        id: 'm1',
        senderId: 'user_1',
        text: 'Olá Maria! Tudo bem? Tenho muito interesse nessa figurinha do Messi. Você aceita diminuir para R$ 320,00?',
        timestamp: '12:05'
      },
      {
        id: 'm2',
        senderId: 'user_2',
        text: 'Olá João! Tudo bem também. Consigo fazer por R$ 330,00 se você puder buscar hoje mesmo no shopping da cidade!',
        timestamp: '12:12'
      },
      {
        id: 'm3',
        senderId: 'user_1',
        text: 'Fechado! Posso ir por volta das 18h no Shopping Esplanada. O que acha?',
        timestamp: '12:15'
      },
      {
        id: 'm4',
        senderId: 'user_2',
        text: 'Ótimo, combinado! Fico no aguardo por lá. Vou levar a figurinha na capinha protetora.',
        timestamp: '12:20'
      }
    ]
  },
  {
    id: 'chat_2',
    stickerId: 'sticker_3',
    buyerId: 'user_2',
    sellerId: 'user_1',
    buyerName: 'Maria Santos',
    sellerName: 'João Silva',
    stickerName: 'Neymar Jr NJR-10',
    stickerImage: 'neymar',
    stickerType: 'troca',
    status: 'active',
    messages: [
      {
        id: 'm5',
        senderId: 'user_2',
        text: 'Olá João! Vi que você quer trocar o Neymar Jr. Você aceita trocar pelo Kane brilhante e mais duas figurinhas comuns?',
        timestamp: '10:30'
      },
      {
        id: 'm6',
        senderId: 'user_1',
        text: 'Hum, eu já tenho o Kane comum, mas queria muito completar o time de Portugal. Você tem alguma repetida portuguesa?',
        timestamp: '10:45'
      }
    ]
  }
];

// Helper functions for localStorage persistence
export function getSavedData<T>(key: string, defaultValue: T): T {
  try {
    const value = localStorage.getItem(`copa_do_mundo_${key}`);
    return value ? JSON.parse(value) : defaultValue;
  } catch (e) {
    return defaultValue;
  }
}

export function saveData<T>(key: string, data: T): void {
  try {
    localStorage.setItem(`copa_do_mundo_${key}`, JSON.stringify(data));
  } catch (e) {
    console.error('Error sharing storage data', e);
  }
}
